// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("WebApi.Models.CuocHoiThoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Daxoavao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Duoccaonhatvao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Duoctaovao")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiHoiThoai")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("NhanVienTaoId")
                        .HasColumnType("int");

                    b.Property<string>("Tieude")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienTaoId");

                    b.ToTable("CuocHoiThoais");
                });

            modelBuilder.Entity("WebApi.Models.NguoiThamGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuocHoiThoaiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Duoccapnhatvao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Duoctaovao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienThamGiaId")
                        .HasColumnType("int");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuocHoiThoaiId");

                    b.HasIndex("NhanVienThamGiaId");

                    b.HasIndex("Userid");

                    b.ToTable("NguoiThamGias");
                });

            modelBuilder.Entity("WebApi.Models.TinNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuocHoiThoaiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Daxoavao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Duoctaovao")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiTinNhan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NhanVienGuiId")
                        .HasColumnType("int");

                    b.Property<string>("Noidung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuocHoiThoaiId");

                    b.HasIndex("NhanVienGuiId");

                    b.HasIndex("Userid");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Models.CuocHoiThoai", b =>
                {
                    b.HasOne("WebApi.Models.User", "NhanVienTao")
                        .WithMany("CuocHoiThoais")
                        .HasForeignKey("NhanVienTaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVienTao");
                });

            modelBuilder.Entity("WebApi.Models.NguoiThamGia", b =>
                {
                    b.HasOne("WebApi.Models.CuocHoiThoai", "CuocHoiThoai")
                        .WithMany("NguoiThamGias")
                        .HasForeignKey("CuocHoiThoaiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebApi.Models.User", "NhanVienThamGia")
                        .WithMany()
                        .HasForeignKey("NhanVienThamGiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebApi.Models.User", null)
                        .WithMany("NguoiThamGias")
                        .HasForeignKey("Userid");

                    b.Navigation("CuocHoiThoai");

                    b.Navigation("NhanVienThamGia");
                });

            modelBuilder.Entity("WebApi.Models.TinNhan", b =>
                {
                    b.HasOne("WebApi.Models.CuocHoiThoai", "CuocHoiThoai")
                        .WithMany("TinNhans")
                        .HasForeignKey("CuocHoiThoaiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebApi.Models.User", "NhanVienGui")
                        .WithMany()
                        .HasForeignKey("NhanVienGuiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebApi.Models.User", null)
                        .WithMany("TinNhans")
                        .HasForeignKey("Userid");

                    b.Navigation("CuocHoiThoai");

                    b.Navigation("NhanVienGui");
                });

            modelBuilder.Entity("WebApi.Models.CuocHoiThoai", b =>
                {
                    b.Navigation("NguoiThamGias");

                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Navigation("CuocHoiThoais");

                    b.Navigation("NguoiThamGias");

                    b.Navigation("TinNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
